sudo: required # super user permissions to execute this build

service:
    - docker     # this will make travis install docker

before_install:
    - docker build -t krishna201294/docker-react -f Dockerfile.dev .  
    # this will return a docker image id, so lets tag it

# will contain list of cmds to be executed
# return code other than 0 means its broken/build failed 
script:
    - docker run -e CI=true krishna201294/docker-react npm run test -- --coverage